name = "wisp-cloudflare"
main = "worker.js"
compatibility_date = "2026-07-06"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[durable_objects.bindings]]
name = "WISP_ROOMS"
class_name = "WispRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WispRoom"]
